name: Update participants map 🗺️

on:
  push:
    branches:
      - main
#    paths:
#      - 'participants.csv'

jobs:
  build:
    name: Generate participants map
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: generate GeoJSON and push to gh-pages 📦
        run: |
          python3 to-geojson.py > participants.geojson
          git push --set-upstream origin gh-pages
          git config --global user.email "tomkralidis@gmail.com"
          git config --global user.name "Tom Kralidis"
          git checkout gh-pages
          git add participants.geojson
          git commit -m "update participants GeoJSON" -a
          git push
